"""
PuroMMA Reels Render Pipeline — GitHub Actions edition  (Stage 1d.4)
Reads JOB_PAYLOAD from environment, renders 3-beat MP4 with kinetic captions,
ES-ES voiceover (Gemini TTS), uploads to Cloudflare R2, optionally POSTs result
to callback_url.

Stage 1d.4 polish vs 1d.3 (Pablo's verdict on Stage 2 batch):
- Music sidechain ducking: bed runs LOUD (volume=5.0, ~-10 dB peak) but is ducked
  ~8 dB whenever voice exceeds -26 dB, releasing over 300 ms. Pablo couldn't hear the
  bed at any prior level (0.07 → 0.18 → 2.0 → 3.0) because phone-speaker dynamic-range
  compression squashes static mixes; the ducker means the bed is clearly present in
  pauses while staying out of the voice's way during speech.
- Image filter: punchier source via eq (contrast=1.10, saturation=1.18, gamma=0.96,
  brightness=0.02) applied before zoompan; stronger unsharp after zoompan
  (luma_msize=5, luma_amount=1.2). Cover image gets the same treatment.

Stage 1d.3 polish vs 1d.2 (Pablo's verdict on reel DY635FYDwNH):
- Bed bumped from volume=2.0 → 3.0 (+50% linear, ~+3.5 dB). Music now ~-15 dB peak
  vs voice peaks at ~-5 dB → ~10 dB separation (slightly under 12-16 dB target but
  Pablo prioritised audibility).
- Event numbers (UFC 329, PFL 7, Bellator 305, etc.) rewritten digit-by-digit for
  TTS only — captions still show "UFC 329" visually but voice now reads
  "UFC tres dos nueve" instead of the cardinal "UFC trescientos veintinueve".
- CTA accent restored: "ENVIASELO" → "ENVÍASELO".
- bed.wav licence still deferred per Pablo (2026-05-29).

Stage 1d.2 fixes vs 1d.1 (and Stage 1c):
- Captions are now keyed off the ACTUAL voiceover text (split by sentence boundary
  into 3 beat-groups, distributed proportionally to TTS character length across the
  narration duration). Previously captions rendered hook/body_beat_1/body_beat_2
  which were independently generated by Gemini and diverged word-for-word from the
  spoken voiceover. Now what's on screen matches what's spoken.
- Readability bar timing (top hook bar vs bottom body bar) follows the same
  proportional beat boundaries, so the bar under the caption is always present.
- Music bed boosted to volume=2.0 (the in-repo bed.wav is integrated -44 LUFS /
  peak -24.5 dBTP, much quieter than the bed render_server.py was tuned against).
  At vol=2.0 music lands at peak ~-18 dB / mean ~-32 dB — voice ~13 dB above bed,
  in Pablo's "voice 12-16 dB above music" target.

Stage 1c changes vs Stage 1b:
- Voiceover constrained to ~30-35 words (~10-13s spoken) → target 12-15s total reel
- Persistent pulsating send-CTA fixed at bottom of reel for entire duration
  (text: "Envíaselo a un colega", alpha pulse 0.6↔1.0 on 1.2s sine cycle,
   pill background, clear of IG UI zones, centered at y≈1500)

Stage 1b changes vs Stage 1:
- ES-ES voiceover via Gemini TTS (Zephyr/Umbriel/Gacrux rotation by wp_post_id % 3)
- Caption timing driven by TTS audio duration (proportional to word length)
- Beat 3 on-screen CTA card removed entirely
- Body beats are complete standalone sentences/phrases, not mid-sentence fragments
"""

import base64, json, os, re, struct, subprocess, sys, tempfile, time, urllib.request, urllib.error

# ── Env / config ──────────────────────────────────────────────────────────────

GEMINI_KEY      = os.environ['GEMINI_API_KEY']
R2_ENDPOINT     = os.environ['R2_ENDPOINT']        # https://<acct>.r2.cloudflarestorage.com
R2_BUCKET       = os.environ['R2_BUCKET_NAME']     # playon-reels
R2_PUBLIC_URL   = os.environ['R2_PUBLIC_URL']      # https://pub-xxx.r2.dev
# R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY are used by aws-cli via env vars
# (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY — set in GH Actions env block)

GEMINI_FLASH    = 'gemini-3-flash-preview'
GEMINI_TTS_MODEL = 'gemini-3.1-flash-tts-preview'
GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models'

# Font path (bundled in repo — Anton Regular, OFL license)
FONT_PATH = os.path.join(os.path.dirname(__file__), '..', 'assets', 'fonts', 'Anton-Regular.ttf')
FONT_PATH = os.path.realpath(FONT_PATH)

MUSIC_PATH = os.path.join(os.path.dirname(__file__), '..', 'assets', 'audio', 'bed.wav')
MUSIC_PATH = os.path.realpath(MUSIC_PATH)

LOGO_PATH = os.path.join(os.path.dirname(__file__), '..', 'assets', 'puromma_logo.png')
LOGO_PATH = os.path.realpath(LOGO_PATH)

FPS      = 25
BEAT_DUR = 3.0   # seconds per beat (3 beats = 9s minimum; extended to fit TTS)
WORK_W   = 2160  # 2× output resolution for zoompan quality
WORK_H   = 3840

# ── TTS voice rotation — peninsular ES-ES, MARCA/COPE energy ──────────────────
PUROMMA_TTS_VOICES = [
    {
        'name':   'Zephyr',
        'gender': 'female',
        'style':  (
            'Lee esto como una analista deportiva española entusiasta — '
            'energía contagiosa, tono apasionado, amistoso y dinámico. '
            'CRÍTICO: acento castellano peninsular (Madrid o Barcelona). '
            'NO acento latinoamericano. NO acento neutro. Pronuncia "z", "ce", '
            '"ci" como /θ/ (zeta española), distinción entre /s/ y /θ/. '
            'Voz vibrante, ritmo deportivo, como introduciendo lo más emocionante '
            'del fin de semana en MARCA TV: '
        ),
    },
    {
        'name':   'Umbriel',
        'gender': 'male',
        'style':  (
            'Lee esto como un comentarista deportivo español apasionado — '
            'energía alta, entusiasta, amistoso, sin gritar ni sonar agresivo. '
            'CRÍTICO: acento castellano peninsular (Madrid o Barcelona). '
            'NO acento latinoamericano. NO acento neutro. Pronuncia "z", "ce", '
            '"ci" como /θ/ (zeta española), distinción entre /s/ y /θ/. '
            'Voz vibrante con clase, como un analista de MARCA o COPE: '
        ),
    },
    {
        'name':   'Gacrux',
        'gender': 'male',
        'style':  (
            'Lee esto como un comentarista deportivo español veterano — '
            'voz madura con autoridad, apasionado pero con clase, '
            'amistoso, sin gritar. CRÍTICO: acento castellano peninsular '
            '(Madrid o Barcelona). NO acento latinoamericano. NO acento neutro. '
            'Pronuncia "z", "ce", "ci" como /θ/ (zeta española), distinción '
            'entre /s/ y /θ/. Tono de analista veterano de MARCA o COPE: '
        ),
    },
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def gemini_json(prompt):
    url = f'{GEMINI_API_BASE}/{GEMINI_FLASH}:generateContent?key={GEMINI_KEY}'
    payload = {
        'contents': [{'parts': [{'text': prompt}]}],
        'generationConfig': {'responseMimeType': 'application/json'},
    }
    data = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=30) as r:
        resp = json.loads(r.read())
    text = resp['candidates'][0]['content']['parts'][0]['text']
    return json.loads(text)


def gemini_tts(text, voice, style_prefix):
    """Call Gemini TTS, return (pcm_bytes, sample_rate)."""
    url = f'{GEMINI_API_BASE}/{GEMINI_TTS_MODEL}:generateContent?key={GEMINI_KEY}'
    payload = {
        'contents': [{'parts': [{'text': style_prefix + text}]}],
        'generationConfig': {
            'responseModalities': ['AUDIO'],
            'speechConfig': {'voiceConfig': {'prebuiltVoiceConfig': {'voiceName': voice}}},
        },
    }
    data = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=60) as r:
        resp = json.loads(r.read())
    part = next(p for p in resp['candidates'][0]['content']['parts'] if 'inlineData' in p)
    mime = part['inlineData']['mimeType']
    raw  = base64.b64decode(part['inlineData']['data'])
    rate = 24000
    for chunk in mime.split(';'):
        if 'rate=' in chunk:
            rate = int(chunk.split('=')[1])
    return raw, rate


def pcm_to_wav(pcm, sr, channels=1, bits=16):
    byte_rate   = sr * channels * bits // 8
    block_align = channels * bits // 8
    data_size   = len(pcm)
    header = b'RIFF' + struct.pack('<I', 36 + data_size) + b'WAVE'
    fmt    = b'fmt ' + struct.pack('<IHHIIHH', 16, 1, channels, sr,
                                   byte_rate, block_align, bits)
    data_c = b'data' + struct.pack('<I', data_size)
    return header + fmt + data_c + pcm


def audio_duration(path):
    r = subprocess.run(
        ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', path],
        capture_output=True, text=True, check=True
    )
    streams = json.loads(r.stdout)['streams']
    for s in streams:
        if s.get('codec_type') == 'audio':
            return float(s['duration'])
    raise RuntimeError(f'No audio stream in {path}')


def download_image(url, dest_path, image_b64=None):
    """Download image from URL, or decode from base64 if image_b64 provided.

    image_b64 is used as fallback when the origin blocks GH Actions runner IPs.
    """
    if image_b64:
        with open(dest_path, 'wb') as f:
            f.write(base64.b64decode(image_b64))
        return
    # Try a browser-like UA first; some WP/Cloudflare setups block curl/urllib defaults
    for ua in (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
        'Mozilla/5.0 (compatible; PuroMMA-bot/1.0)',
    ):
        req = urllib.request.Request(url, headers={'User-Agent': ua})
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                with open(dest_path, 'wb') as f:
                    f.write(r.read())
            return
        except urllib.error.HTTPError as e:
            if e.code == 403:
                continue
            raise
    raise RuntimeError(f'Image download failed with 403 for all user-agents: {url}')


def ffprobe_image_dims(path):
    r = subprocess.run(
        ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_streams', path],
        capture_output=True, text=True, check=True
    )
    s = json.loads(r.stdout)['streams'][0]
    return int(s['width']), int(s['height'])


def sanitise_drawtext(s):
    """Escape characters that break FFmpeg drawtext filter."""
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "’")   # curly apostrophe — safe in drawtext
    s = s.replace(':', '\\:')
    s = s.replace('%', '\\%')
    return s


# ── TTS pronunciation shaping ─────────────────────────────────────────────────

_ES_DIGIT_WORDS = {
    '0': 'cero', '1': 'uno', '2': 'dos', '3': 'tres', '4': 'cuatro',
    '5': 'cinco', '6': 'seis', '7': 'siete', '8': 'ocho', '9': 'nueve',
}

# Match common MMA event labels followed by an event number (e.g. "UFC 329",
# "ufc fight night 251", "PFL 7", "Bellator 305", "ONE 165").
_EVENT_NUMBER_RE = re.compile(
    r'\b(UFC(?:\s+Fight\s+Night)?|UFC\s+FN|UFC\s+on\s+ESPN|UFC\s+APEX|'
    r'PFL|Bellator|ONE|RIZIN|KSW|Cage\s+Warriors)'
    r'(\s+)(\d{2,4})\b',
    flags=re.IGNORECASE,
)


def spell_event_numbers_for_tts(text):
    """Rewrite event numbers as digit-by-digit Spanish for the TTS pass only.

    Pablo's 1d.3 verdict: Gemini TTS reads 'UFC 329' as 'UFC trescientos veintinueve'
    (cardinal). For sports event numbering Pablo wants digit-by-digit:
    'UFC tres dos nueve'. This rewrite is applied ONLY to the text fed to TTS — the
    voiceover field used for on-screen captions keeps the numerals so the caption
    reads "UFC 329" visually.

    Returns the rewritten string.
    """
    if not text:
        return text
    def repl(m):
        label, gap, num = m.group(1), m.group(2), m.group(3)
        spelled = ' '.join(_ES_DIGIT_WORDS[d] for d in num)
        return f"{label}{gap}{spelled}"
    return _EVENT_NUMBER_RE.sub(repl, text)


# ── Content generation ────────────────────────────────────────────────────────

def generate_content(post_title, image_url, content_type='news_hook'):
    """Call Gemini to produce structured content for the reel.

    Returns dict with:
      fighter_name, hook_text, body_beat_1, body_beat_2,
      voiceover, ig_caption
    """
    prompt = f"""You are a social-media content writer for PuroMMA (puromma.com),
a Spanish-language MMA site targeting a peninsular Spanish audience (Spain).

Language: ES-ES peninsular Spanish. Use vosotros/os. Use /θ/ distinction in writing
(e.g. "veréis", "conocéis"). Never use LatAm "ustedes" as default second person plural.

Article title: {post_title}
Content type: {content_type}

Return ONLY valid JSON with exactly these keys:

- fighter_name: Main fighter's name in ALL CAPS, 1-3 words (e.g. "MCGREGOR")

- hook_text: A 5-8 word hook in ALL CAPS, ES-ES peninsular. Provocative — opens a
  curiosity gap or delivers a hot take. Must be a COMPLETE, grammatical, standalone
  phrase that makes sense on its own.
  Example: "LA PREDICCIÓN QUE NADIE QUERÍA OÍR"

- body_beat_1: A COMPLETE, self-contained sentence or phrase in ALL CAPS, 8-14 words.
  This appears alone on screen — it MUST make full grammatical sense on its own, with
  no dependency on surrounding beats. No cliffhangers mid-sentence.
  Example: "MATT BROWN CREE QUE MCGREGOR SE RETIRARÁ SI NO PELEA EN UFC 329"

- body_beat_2: A COMPLETE, self-contained sentence or phrase in ALL CAPS, 8-14 words.
  Same rules as body_beat_1 — standalone, grammatically complete, no mid-sentence cut.
  Example: "EL VETERANO AMERICANO DA SU PREDICCIÓN MÁS DEMOLEDORA HASTA LA FECHA"

- voiceover: CONCISE narration in ES-ES peninsular Spanish. HARD LIMIT: 30-35 words MAX
  (count carefully — this is spoken aloud and must fit ~10-13 seconds).
  Structure: sharp hook (1 sentence) → key fact (1 sentence) → punchy closer (1 sentence).
  Each sentence must be tight — no filler, no padding.
  End with a punchy 3-5 word closing line (e.g. "Esto lo cambia todo." or "La pregunta es cuándo.").
  NO send/share/forward calls-to-action in the voiceover.
  Use vosotros/os forms. Pronounce-aware: write out /θ/ words naturally.
  CRÍTICO: para números de eventos (UFC 329, UFC Fight Night 251, Bellator 305,
  PFL 7, ONE 165, etc.) escribe SIEMPRE el número como dígitos ("UFC 329"),
  NUNCA como cardinal escrito ("UFC trescientos veintinueve"). El post-procesamiento
  de TTS lee los dígitos uno a uno ("UFC tres dos nueve") — esto solo funciona
  si llegan como dígitos. Misma regla para body_beat_1 y body_beat_2.

- ig_caption: Instagram caption in ES-ES peninsular Spanish, max 180 words before hashtags.
  Format: keyword-rich opening line (15-25 words) + blank line + 2-3 sentences of
  connected prose (no bullet fragments) + blank line + soft save/share CTA line + blank line +
  5 hashtags on last line: #MMAEspaña #UFC #peleadoresespañoles #MMAEspanol #PuroMMA
"""
    return gemini_json(prompt)


# ── Cover image ───────────────────────────────────────────────────────────────

def make_cover(image_url, tmp_dir, image_b64=None):
    """Download + FFmpeg to 1080x1920 brightened JPEG. Returns path."""
    src = os.path.join(tmp_dir, 'cover_src.jpg')
    out = os.path.join(tmp_dir, 'cover.jpg')
    download_image(image_url, src, image_b64=image_b64)
    subprocess.run([
        'ffmpeg', '-y', '-i', src,
        '-vf', (
            # Stage 1d.4: match the punchier filter applied per beat in the reel.
            'scale=1080:1920:force_original_aspect_ratio=increase,'
            'crop=1080:1920,'
            'eq=contrast=1.10:saturation=1.18:gamma=0.96:brightness=0.05,'
            'unsharp=luma_msize_x=5:luma_msize_y=5:luma_amount=1.0'
        ),
        '-q:v', '3', out
    ], capture_output=True, check=True)
    return out


# ── FFmpeg render ─────────────────────────────────────────────────────────────

def build_beat_zoompan(beat_idx, n_frames):
    """Return zoompan expression string for one beat."""
    if beat_idx == 0:
        # Beat 1: tight center crop, zoom in 1.0→1.35
        z = f"'min(1.0+0.35/{n_frames}*on,1.35)'"
        x = "'iw/2-(iw/zoom/2)'"
        y = "'ih/2-(ih/zoom/2)'"
    elif beat_idx == 1:
        # Beat 2: pan left-to-right with mild zoom 1.1→1.25
        z = f"'min(1.1+0.15/{n_frames}*on,1.25)'"
        x = f"'min(max(iw*0.08*(on/{n_frames}),0),iw-iw/zoom)'"
        y = "'ih/2-(ih/zoom/2)'"
    else:
        # Beat 3: pull-back from 1.35→1.0 (matches beat 1 start — enables seamless loop)
        z = f"'max(1.35-0.35/{n_frames}*on,1.0)'"
        x = "'iw/2-(iw/zoom/2)'"
        y = "'ih/2-(ih/zoom/2)'"
    return z, x, y


def build_drawtext_filters(words_schedule, font_path):
    """
    Build a list of drawtext filter strings for word-by-word kinetic captions.
    words_schedule: list of dicts {word, t_start, t_end, beat, size, color, y_pos}
    """
    filters = []
    font_esc = font_path.replace('\\', '/').replace(':', '\\:')

    for i, w in enumerate(words_schedule):
        word = sanitise_drawtext(w['word'])
        color = w.get('color', 'white')
        size  = w.get('size', 84)
        y_pos = w.get('y_pos', 350)
        t0    = w['t_start']
        t1    = w['t_end']

        # Main word
        f = (
            f"drawtext=fontfile='{font_esc}':"
            f"text='{word}':"
            f"fontsize={size}:fontcolor={color}:"
            f"x='(w-tw)/2':y={y_pos}:"
            f"shadowcolor=black@0.85:shadowx=3:shadowy=3:"
            f"enable='between(t,{t0:.3f},{t1:.3f})'"
        )
        filters.append(f)

        # Ghost of previous word (brief fade-out echo)
        if i > 0 and words_schedule[i-1]['beat'] == w['beat']:
            prev = words_schedule[i-1]
            prev_word = sanitise_drawtext(prev['word'])
            prev_size = int(prev.get('size', 84) * 0.92)
            ghost = (
                f"drawtext=fontfile='{font_esc}':"
                f"text='{prev_word}':"
                f"fontsize={prev_size}:fontcolor={prev.get('color','white')}@0.30:"
                f"x='(w-tw)/2':y={prev.get('y_pos', 350)}:"
                f"shadowcolor=black@0.3:shadowx=2:shadowy=2:"
                f"enable='between(t,{t0:.3f},{min(t0+0.25, t1):.3f})'"
            )
            filters.append(ghost)

    return filters


def split_voiceover_into_beats(voiceover_text, n_beats=3):
    """Split spoken voiceover into n_beats text groups by sentence boundary.

    - >=n_beats sentences: first (n_beats-1) become beats 1..n-1, the rest are merged
      into the final beat.
    - exactly n_beats: 1:1.
    - 2 sentences (n_beats=3): split the longer one on the first comma/semicolon.
    - 1 sentence: split on commas/semicolons; merge tail into last beat. If no
      comma boundaries, pad later beats with empty strings.
    - 0 sentences: all empty strings.

    Returns list[str] of length n_beats.
    """
    raw = re.split(r'(?<=[.!?…])\s+', (voiceover_text or '').strip())
    sents = [s.strip() for s in raw if s.strip()]

    if not sents:
        return [''] * n_beats

    if len(sents) == n_beats:
        return sents

    if len(sents) > n_beats:
        head = sents[:n_beats - 1]
        tail = ' '.join(sents[n_beats - 1:])
        return head + [tail]

    # len(sents) < n_beats — need to split for visual rhythm
    if len(sents) == 1:
        parts = re.split(r'(?<=[,;])\s+', sents[0])
        parts = [p.strip() for p in parts if p.strip()]
        if len(parts) >= n_beats:
            return parts[:n_beats - 1] + [' '.join(parts[n_beats - 1:])]
        # Not enough comma chunks — pad with empty
        return parts + [''] * (n_beats - len(parts))

    # 2 sentences, n_beats=3: split the longer one on first comma/semicolon
    if len(sents) == 2 and n_beats == 3:
        target_idx = 0 if len(sents[0]) >= len(sents[1]) else 1
        target = sents[target_idx]
        parts = re.split(r'(?<=[,;])\s+', target, maxsplit=1)
        if len(parts) == 2:
            split_first, split_second = parts[0].strip(), parts[1].strip()
            if target_idx == 0:
                return [split_first, split_second, sents[1]]
            else:
                return [sents[0], split_first, split_second]
        # No comma — pad with empty in the middle
        return [sents[0], '', sents[1]] if target_idx == 0 else [sents[0], sents[1], '']

    # General fallback — pad
    return sents + [''] * (n_beats - len(sents))


def schedule_words_from_voiceover(voiceover_text, narr_duration, n_beats=3):
    """Time-distribute the actual spoken voiceover across the narration timeline.

    Splits the voiceover into n_beats sentence-groups, allocates a time slice to each
    beat proportional to its character length, then distributes words within each slice
    proportional to word character length.

    Beat styling matches Stage 1c: beat 0 = hook position (top, big), beats 1+2 = body
    position (middle, smaller).

    Returns (schedule, beat_end_times):
      schedule:        list of word dicts {word, beat, t_start, t_end, size, color, y_pos}
      beat_end_times:  list of length n_beats with cumulative end timestamps per beat
    """
    beat_texts = split_voiceover_into_beats(voiceover_text, n_beats=n_beats)

    beat_styles = [
        {'size': 96, 'color': 'white', 'y_pos': 320},   # hook position
        {'size': 80, 'color': 'white', 'y_pos': 800},   # body
        {'size': 80, 'color': 'white', 'y_pos': 800},   # body
    ]

    # Weight each beat by character length (so longer sentences get more screen time)
    lengths = [max(len(t), 1) if t else 0 for t in beat_texts]
    total_len = sum(lengths) or 1

    # If any beat has weight 0 (no text), reserve a tiny floor so cumulative end times
    # progress monotonically — but don't display anything in that slot.
    floor_share = 0.0
    if any(l == 0 for l in lengths):
        floor_share = narr_duration * 0.02   # 2% per empty beat, harmless

    schedule = []
    beat_end_times = []
    t = 0.0
    for i, (txt, length, style) in enumerate(zip(beat_texts, lengths, beat_styles)):
        if length > 0:
            slot_dur = narr_duration * (length / total_len)
        else:
            slot_dur = floor_share
        t_start = t
        t_end = min(t + slot_dur, narr_duration)
        # For the last beat with content, snap to narr_duration to avoid trailing gap
        if i == n_beats - 1 and length > 0:
            t_end = narr_duration
        beat_end_times.append(round(t_end, 3))
        t = t_end

        if not txt:
            continue

        words = txt.upper().split()
        if not words:
            continue

        word_lengths = [max(len(w), 1) for w in words]
        total_wl = sum(word_lengths)
        available = max(t_end - t_start - 0.15, 0.1)
        tw = t_start + 0.08
        for word, wl in zip(words, word_lengths):
            hold = max(available * (wl / total_wl), 0.22)
            tw_end = min(tw + hold, t_end - 0.05)
            schedule.append({
                'word':    word,
                'beat':    i,
                't_start': round(tw, 3),
                't_end':   round(tw_end, 3),
                'size':    style['size'],
                'color':   style['color'],
                'y_pos':   style['y_pos'],
            })
            tw = tw_end
            if tw >= t_end - 0.05:
                break

    return schedule, beat_end_times


def schedule_words_from_voice(hook_text, body_beat_1, body_beat_2,
                               tts_duration, beat_dur):
    """[DEPRECATED in 1d.2] Distribute hook/body_beat_1/body_beat_2 across timeline.

    Kept for reference / fallback only. The active caption scheduler is
    schedule_words_from_voiceover(), which keys captions off the actual spoken text.

    - Beat 1 (0 → beat_dur): hook_text
    - Beat 2 (beat_dur → beat_dur*2): body_beat_1
    - Beat 3 (beat_dur*2 → tts_duration): body_beat_2  [NO CTA card]

    Timing within each beat is proportional to word character length,
    matching the natural pace of spoken narration.

    Returns list of word timing dicts.
    """
    total_dur = tts_duration
    schedule  = []

    def _distribute(words, t_start, t_end, beat, size, color, y_pos):
        """Spread word display times proportionally across [t_start, t_end]."""
        if not words:
            return
        # weight by character length (longer words get slightly more screen time)
        lengths = [max(len(w), 1) for w in words]
        total_len = sum(lengths)
        available = t_end - t_start - 0.1   # small lead-in
        t = t_start + 0.12  # small lead-in before first word
        for word, char_len in zip(words, lengths):
            hold = available * (char_len / total_len)
            hold = max(hold, 0.22)   # minimum 220ms so short words are readable
            t_end_w = min(t + hold, t_end - 0.05)
            schedule.append({
                'word': word, 'beat': beat,
                't_start': round(t, 3), 't_end': round(t_end_w, 3),
                'size': size, 'color': color, 'y_pos': y_pos
            })
            t = t_end_w
            if t >= t_end - 0.05:
                break

    # Beat 1: hook
    _distribute(
        hook_text.upper().split(),
        t_start=0.0, t_end=beat_dur,
        beat=0, size=96, color='white', y_pos=320
    )

    # Beat 2: body_beat_1
    _distribute(
        body_beat_1.upper().split() if body_beat_1 else [],
        t_start=beat_dur, t_end=beat_dur * 2,
        beat=1, size=80, color='white', y_pos=800
    )

    # Beat 3: body_beat_2  (NO CTA — removed per feedback)
    _distribute(
        body_beat_2.upper().split() if body_beat_2 else [],
        t_start=beat_dur * 2, t_end=total_dur,
        beat=2, size=80, color='white', y_pos=800
    )

    return schedule


def render_video(img_path, narr_path, narr_duration, content, tmp_dir):
    """
    Build 3-beat hard-cut reel with kinetic captions + ES-ES voiceover.
    Video duration = max(3 beats × BEAT_DUR, narr_duration + 0.5s tail).
    Returns path to rendered MP4.
    """
    hook_text    = content.get('hook_text', content.get('headline', 'PURO MMA'))
    body_beat_1  = content.get('body_beat_1', content.get('body_text', ''))
    body_beat_2  = content.get('body_beat_2', '')
    fighter      = content.get('fighter_name', '')

    # Video length: long enough to fit voiceover + short tail
    total_dur = max(BEAT_DUR * 3, narr_duration + 0.4)
    # Snap to 3-beat grid (avoid partial beats at end)
    beat_3_end = total_dur
    print(f'  Video duration: {total_dur:.2f}s (TTS: {narr_duration:.2f}s)')

    out_path = os.path.join(tmp_dir, 'reel.mp4')
    n_frames = int(BEAT_DUR * FPS)  # frames per beat (fixed 3s each)

    # Build 3-beat filter_complex
    # Stage 1d.4 image filter: punchier source before zoompan (eq contrast/saturation/
    # gamma) + stronger unsharp after zoompan. Pablo's verdict on Stage 2: "needs filter
    # for sharpness and color balance" on reels 4 + 5.
    beat_segments = []
    for bi in range(3):
        z, x, y = build_beat_zoompan(bi, n_frames)
        seg = (
            f"[0:v] scale={WORK_W}:{WORK_H}:force_original_aspect_ratio=increase:flags=lanczos,"
            f"crop={WORK_W}:{WORK_H},"
            f"eq=contrast=1.10:saturation=1.18:gamma=0.96:brightness=0.02,"
            f"zoompan=z={z}:x={x}:y={y}:d={n_frames}:s=1080x1920:fps={FPS},"
            f"unsharp=luma_msize_x=5:luma_msize_y=5:luma_amount=1.2"
            f" [b{bi}]"
        )
        beat_segments.append(seg)

    fc_parts = beat_segments
    fc_parts.append("[b0][b1][b2] concat=n=3:v=1:a=0 [pre_text]")

    # Stage 1d.2 fix: caption the ACTUAL voiceover text, split into 3 beat-groups
    # by sentence boundary, distributed proportionally across narration time.
    # Previously captions used hook/body_beat_1/body_beat_2 (independently generated
    # text fields that diverged word-for-word from the spoken voiceover).
    voiceover_text = content.get('voiceover', '') or ''
    words_schedule, beat_end_times = schedule_words_from_voiceover(
        voiceover_text, narr_duration=narr_duration, n_beats=3
    )
    # Fallback: if the voiceover came back empty for some reason, restore the legacy
    # hook/body_beat layout so we still ship a usable reel.
    if not words_schedule:
        legacy = schedule_words_from_voice(
            hook_text, body_beat_1, body_beat_2,
            tts_duration=narr_duration, beat_dur=BEAT_DUR
        )
        words_schedule = legacy
        beat_end_times = [BEAT_DUR, BEAT_DUR * 2, narr_duration]
    caption_filters = build_drawtext_filters(words_schedule, FONT_PATH)

    # Beat-1 (hook position) end time — used by the hook readability bar + red rule.
    # Falls back to BEAT_DUR if the scheduler returned no beats (defensive).
    beat_1_end = beat_end_times[0] if beat_end_times else BEAT_DUR

    # Fighter name watermark (bottom-centre, subtle)
    font_esc = FONT_PATH.replace('\\', '/').replace(':', '\\:')
    if fighter:
        fighter_safe = sanitise_drawtext(fighter)
        caption_filters.append(
            f"drawtext=fontfile='{font_esc}':"
            f"text='{fighter_safe}':"
            f"fontsize=38:fontcolor=white@0.55:"
            f"x='(w-tw)/2':y=1780:"
            f"shadowcolor=black@0.5:shadowx=2:shadowy=2"
        )

    # Red accent rule — horizontal line below hook beat only.
    # Stage 1d.2: tracks the proportional hook-beat end time (not fixed BEAT_DUR),
    # so the rule disappears in lock-step with the hook caption.
    caption_filters.append(
        f"drawbox=x=60:y=430:w=960:h=4:color=#FF4444@0.85:t=fill:"
        f"enable='lte(t,{beat_1_end:.2f})'"
    )

    # Persistent pulsating send-CTA — full duration, bottom of reel
    # Safe zone analysis (1080x1920 canvas):
    #   - IG bottom UI (caption / progress / controls): y > ~1640 — off limits
    #   - Body captions sit around y=800 — >650px above this CTA — no collision
    # Pill: semi-transparent black bar, centred horizontally, y≈1480-1550
    # Text pulses alpha 0.6↔1.0 on a 1.2s sine cycle (smooth, never hard-blink)
    # Red accent: thin drawbox underline below the text (always-on, same alpha pulse not
    # possible for drawbox, so it stays at constant alpha 0.75 — subtle enough)
    cta_text    = "ENVÍASELO A UN COLEGA"   # 1d.3: restored Í accent per Pablo
    cta_pill_x  = 270
    cta_pill_y  = 1476   # top of pill
    cta_pill_w  = 540
    cta_pill_h  = 60     # pill height → centre ≈ y1506
    cta_text_y  = 1482   # drawtext y (baseline ≈ centre of pill)
    cta_accent_y = cta_pill_y + cta_pill_h + 2   # thin red line just below pill
    cta_pulse   = "0.6+0.4*abs(sin(2*PI*t/1.2))"
    # Pill background (constant — provides legibility even when text is at min alpha)
    caption_filters.append(
        f"drawbox=x={cta_pill_x}:y={cta_pill_y}:w={cta_pill_w}:h={cta_pill_h}:"
        f"color=black@0.55:t=fill"
    )
    # Pulsating CTA text (white, Anton, centred in pill)
    cta_safe = sanitise_drawtext(cta_text)
    caption_filters.append(
        f"drawtext=fontfile='{font_esc}':"
        f"text='{cta_safe}':"
        f"fontsize=28:fontcolor=white:"
        f"alpha='{cta_pulse}':"
        f"x='(w-tw)/2':y={cta_text_y}:"
        f"shadowcolor=black@0.7:shadowx=2:shadowy=2"
    )
    # Red accent underline below pill (PuroMMA brand colour, constant)
    caption_filters.append(
        f"drawbox=x={cta_pill_x}:y={cta_accent_y}:w={cta_pill_w}:h=3:"
        f"color=#FF4444@0.75:t=fill"
    )

    # Dark overlay bars for readability.
    # Stage 1d.2: bars switch at the proportional beat-1 end time so the bar always
    # sits under the visible caption (top bar for hook, bottom bar for body beats).
    readability = [
        # Hook beat background bar (visible while hook caption is on screen)
        f"drawbox=x=0:y=270:w=1080:h=200:color=black@0.55:t=fill:"
        f"enable='lte(t,{beat_1_end:.2f})'",
        # Body beats background bar (visible from end of hook beat onward)
        f"drawbox=x=0:y=755:w=1080:h=140:color=black@0.50:t=fill:"
        f"enable='gte(t,{beat_1_end:.2f})'",
    ]

    all_text_filters = ','.join(readability + caption_filters)
    fc_parts.append(f"[pre_text] {all_text_filters} [v_text]")

    # Logo overlay
    has_logo = os.path.exists(LOGO_PATH)
    logo_w   = int(1080 * 0.13)
    if has_logo:
        fc_parts.append(f"[2:v] scale={logo_w}:-1 [logo]")
        logo_x = 1080 - logo_w - 20
        logo_y = 1920 - logo_w - 20
        fc_parts.append(
            f"[v_text][logo] overlay={logo_x}:{logo_y}:format=auto,"
            f"format=yuv420p,"
            f"setparams=range=tv:color_primaries=bt709:color_trc=bt709:colorspace=bt709 [v]"
        )
    else:
        fc_parts.append(
            f"[v_text] format=yuv420p,"
            f"setparams=range=tv:color_primaries=bt709:color_trc=bt709:colorspace=bt709 [v]"
        )

    # Audio: music bed (vol 0.07) + voiceover (vol 1.0), amix
    fade_out_st = total_dur - 1.5
    music_fade_out = max(fade_out_st, 0.0)
    narr_fade_out  = max(narr_duration - 0.4, 0.0)
    narr_input_idx = 3 if has_logo else 2

    # Stage 1d.4: sidechain ducking on the bed. Pablo's verdict on Stage 2 (after
    # 0.07→0.18→2.0→3.0 boosts) — bed still inaudible. The cause is phone-speaker
    # dynamic-range compression: a static mix where voice dominates by 10+ dB makes
    # the bed disappear regardless of absolute level. Fix: run the bed LOUD at base
    # (volume=5.0, peak ~-10.5 dB) but compress it via sidechaincompress keyed to
    # the voice signal. Bed pulls down ~8 dB whenever voice is loud, releases over
    # 300 ms when voice stops. Effect on a phone: bed is clearly audible in the
    # micro-pauses between words and at start/end, voice stays clean during speech.
    fc_parts.append(
        f"[1:a] atrim=0:{total_dur},asetpts=PTS-STARTPTS,"
        f"volume=5.0,"
        f"afade=t=in:st=0:d=0.8,"
        f"afade=t=out:st={music_fade_out:.2f}:d=1.4 [music_raw]"
    )
    fc_parts.append(
        f"[{narr_input_idx}:a] volume=1.0,"
        f"afade=t=in:st=0:d=0.15,"
        f"afade=t=out:st={narr_fade_out:.2f}:d=0.4 [narr]"
    )
    # Split voice: one copy drives the sidechain key, the other goes into the mix.
    fc_parts.append("[narr] asplit=2 [narr_main][narr_sc]")
    # Duck the bed when voice exceeds ~-26 dB. ratio=8 is aggressive but musical.
    # attack=10ms grabs the bed quickly when voice starts; release=300ms eases it back
    # gradually so transitions don't feel pumped.
    fc_parts.append(
        "[music_raw][narr_sc] sidechaincompress="
        "threshold=0.05:ratio=8:attack=10:release=300:makeup=1:level_sc=1.0 [music_ducked]"
    )
    fc_parts.append(
        "[music_ducked][narr_main] amix=inputs=2:duration=first:normalize=0 [audio]"
    )

    filter_complex = '; '.join(fc_parts)

    # Build inputs: image, music, (logo), narration
    inputs = [
        '-loop', '1', '-framerate', str(FPS), '-t', str(total_dur + 0.5), '-i', img_path,
        '-i', MUSIC_PATH,
    ]
    if has_logo:
        inputs += ['-i', LOGO_PATH]
    inputs += ['-i', narr_path]

    cmd = (
        ['ffmpeg', '-y'] + inputs +
        [
            '-filter_complex', filter_complex,
            '-map', '[v]', '-map', '[audio]',
            '-c:v', 'libx264', '-preset', 'fast', '-crf', '18', '-profile:v', 'high',
            '-movflags', '+faststart',
            '-pix_fmt', 'yuv420p',
            '-c:a', 'aac', '-b:a', '128k', '-ar', '44100', '-ac', '2',
            '-t', str(total_dur), '-r', str(FPS),
            out_path
        ]
    )

    print(f'  FFmpeg render ({total_dur:.2f}s, 3 beats + voice)...')
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        stderr_tail = (result.stderr or '')[-4000:]
        print(f'  FFmpeg stderr:\n{stderr_tail}')
        raise RuntimeError(f'FFmpeg failed (rc={result.returncode})')
    print(f'  Render complete: {out_path}')
    return out_path, total_dur


# ── R2 upload ─────────────────────────────────────────────────────────────────

def upload_to_r2(local_path, object_key, content_type):
    """Upload file to R2 via aws-cli (pre-installed on ubuntu-latest)."""
    cmd = [
        'aws', 's3', 'cp', local_path,
        f's3://{R2_BUCKET}/{object_key}',
        '--endpoint-url', R2_ENDPOINT,
        '--content-type', content_type,
        '--no-progress',
    ]
    print(f'  Uploading {object_key} → R2...')
    result = subprocess.run(cmd, capture_output=True, text=True, env=dict(
        os.environ,
        AWS_ACCESS_KEY_ID=os.environ['R2_ACCESS_KEY_ID'],
        AWS_SECRET_ACCESS_KEY=os.environ['R2_SECRET_ACCESS_KEY'],
        AWS_DEFAULT_REGION='auto',
    ))
    if result.returncode != 0:
        raise RuntimeError(f'R2 upload failed: {result.stderr[:500]}')
    public_url = f'{R2_PUBLIC_URL.rstrip("/")}/{object_key}'
    print(f'  Uploaded: {public_url}')
    return public_url


# ── Callback ──────────────────────────────────────────────────────────────────

def post_callback(callback_url, payload, token=None):
    if not callback_url:
        print('  No callback_url — skipping callback.')
        return
    headers = {'Content-Type': 'application/json'}
    if token:
        headers['Authorization'] = f'Bearer {token}'
    data = json.dumps(payload).encode()
    req = urllib.request.Request(callback_url, data=data, headers=headers, method='POST')
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            print(f'  Callback → {r.status}')
    except Exception as e:
        print(f'  Callback failed (non-fatal): {e}')


# ── Main pipeline ─────────────────────────────────────────────────────────────

def main():
    raw_payload = os.environ.get('JOB_PAYLOAD', '{}')
    job = json.loads(raw_payload)

    job_id       = job.get('job_id', f"puromma_{int(time.time())}")
    post_title   = job.get('post_title', 'PuroMMA Article')
    image_url    = job.get('image_url', '')
    image_b64    = job.get('image_b64', None)   # optional: base64-encoded image bytes
    wp_post_id   = job.get('wp_post_id', '0')
    content_type = job.get('content_type', 'news_hook')
    callback_url = job.get('callback_url', '')
    n8n_token    = os.environ.get('N8N_CALLBACK_TOKEN', '')

    print(f'=== PuroMMA Render Pipeline (Stage 1d.4) ===')
    print(f'  job_id: {job_id}')
    print(f'  post_title: {post_title[:80]}')
    print(f'  content_type: {content_type}')
    print(f'  wp_post_id: {wp_post_id}')
    print(f'  font: {FONT_PATH}')

    if not image_url:
        raise ValueError('image_url is required in JOB_PAYLOAD')

    # TTS voice rotation: deterministic by wp_post_id % 3
    try:
        voice_idx = int(wp_post_id) % len(PUROMMA_TTS_VOICES)
    except (ValueError, TypeError):
        voice_idx = 0
    chosen_voice = PUROMMA_TTS_VOICES[voice_idx]
    print(f'  TTS voice: {chosen_voice["name"]} ({chosen_voice["gender"]}) '
          f'[wp_post_id={wp_post_id}, idx={voice_idx}]')

    ts = int(time.time())
    filename       = f'puromma_{wp_post_id}_{ts}.mp4'
    cover_filename = f'puromma_{wp_post_id}_{ts}_cover.jpg'

    tmp_dir = tempfile.mkdtemp(prefix='reel_')

    try:
        # 1. Content generation
        print('  Generating content (Gemini)...')
        content = generate_content(post_title, image_url, content_type)
        print(f"  fighter: {content.get('fighter_name')}")
        print(f"  hook: {content.get('hook_text', '')[:60]}")
        print(f"  body_beat_1: {content.get('body_beat_1', '')[:70]}")
        print(f"  body_beat_2: {content.get('body_beat_2', '')[:70]}")
        print(f"  voiceover: {content.get('voiceover', '')[:100]}")

        # Allow payload overrides
        if job.get('hook_text'):
            content['hook_text'] = job['hook_text']

        # 2. TTS — ES-ES voiceover
        # 1d.3: rewrite event numbers (UFC 329 etc.) digit-by-digit FOR TTS ONLY —
        # captions still see the numerals via content['voiceover'] (looks right on screen,
        # reads right out loud).
        narr_path = os.path.join(tmp_dir, 'narration.wav')
        voiceover_text = content.get('voiceover', post_title)
        tts_text = spell_event_numbers_for_tts(voiceover_text)
        if tts_text != voiceover_text:
            print(f'  TTS text rewrite (event numbers): {tts_text[:120]}')
        print(f'  TTS ({chosen_voice["name"]}, ES-ES)...')
        pcm, rate = gemini_tts(tts_text, chosen_voice['name'], chosen_voice['style'])
        with open(narr_path, 'wb') as f:
            f.write(pcm_to_wav(pcm, rate))
        narr_dur = audio_duration(narr_path)
        print(f'  Narration duration: {narr_dur:.2f}s')

        # 3. Download fighter image (or decode from base64 if origin blocks runner IPs)
        img_path = os.path.join(tmp_dir, 'fighter.jpg')
        if image_b64:
            print(f'  Decoding image from base64 payload ({len(image_b64)} chars)...')
        else:
            print(f'  Downloading image: {image_url[:80]}...')
        download_image(image_url, img_path, image_b64=image_b64)

        # 4. Render video (voice-synced captions, no CTA card)
        mp4_path, video_dur = render_video(img_path, narr_path, narr_dur, content, tmp_dir)

        # 5. Cover image
        print('  Generating cover...')
        cover_path = make_cover(image_url, tmp_dir, image_b64=image_b64)

        # 6. Upload to R2
        video_url = upload_to_r2(mp4_path, filename, 'video/mp4')
        cover_url = upload_to_r2(cover_path, cover_filename, 'image/jpeg')

        # 7. Summary
        ig_caption = content.get('ig_caption', post_title)

        summary_lines = [
            '## PuroMMA Render Complete (Stage 1d.4)',
            f'- **Job ID:** {job_id}',
            f'- **Fighter:** {content.get("fighter_name", "?")}',
            f'- **Hook:** {content.get("hook_text", "?")}',
            f'- **TTS Voice:** {chosen_voice["name"]} ({chosen_voice["gender"]})',
            f'- **Duration:** {video_dur:.2f}s (TTS: {narr_dur:.2f}s)',
            f'- **Video URL:** {video_url}',
            f'- **Cover URL:** {cover_url}',
            f'- **IG Caption (first 200 chars):** {ig_caption[:200]}',
        ]
        print('\n'.join(summary_lines))

        summary_file = os.environ.get('GITHUB_STEP_SUMMARY')
        if summary_file:
            with open(summary_file, 'a') as f:
                f.write('\n'.join(summary_lines) + '\n')

        output_file = os.environ.get('GITHUB_OUTPUT')
        if output_file:
            with open(output_file, 'a', encoding='utf-8') as f:
                f.write(f'video_url={video_url}\n')
                f.write(f'cover_url={cover_url}\n')
                caption_safe = ig_caption[:500].replace('\r', '')
                delim = 'EOF_CAPTION'
                f.write(f'ig_caption<<{delim}\n{caption_safe}\n{delim}\n')

        result_payload = {
            'job_id':     job_id,
            'status':     'success',
            'video_url':  video_url,
            'cover_url':  cover_url,
            'ig_caption': ig_caption,
            'duration':   video_dur,
            'filename':   filename,
            'tts_voice':  chosen_voice['name'],
        }
        post_callback(callback_url, result_payload, n8n_token)

        print('=== Pipeline complete ===')

    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(f'PIPELINE ERROR: {tb}')
        error_payload = {
            'job_id': job_id,
            'status': 'error',
            'error':  str(e),
        }
        post_callback(callback_url, error_payload, n8n_token)
        sys.exit(1)

    finally:
        import shutil
        try:
            shutil.rmtree(tmp_dir)
        except Exception:
            pass


if __name__ == '__main__':
    main()
